# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='Not name', max_length=60),
        ),
    ]
